addpath('Training_data_V');
data = load('Training_data_V.mat');
trainingData = data.trainingData;

%net = mobilenetv2();
net =darknet19();
analyzeNetwork(net)
%lgraph = layerGraph(net);
anchorBoxes=[18 18; 35 35];
imageSize=[512 640 3];
numClasses =4;
featureLayer="leaky17";
lgraph = yolov2Layers(imageSize,numClasses,anchorBoxes,net,featureLayer);

options = trainingOptions('adam', ...
    'InitialLearnRate', 0.005, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropFactor', 0.1, ...
    'LearnRateDropPeriod', 10, ...
    'MiniBatchSize', 16, ...
    'MaxEpochs', 1, ...
    'Shuffle', 'every-epoch', ...
    'Verbose', true, ...
    'VerboseFrequency', 25, ...
    'CheckpointPath', tempdir);

[detector,info] = trainYOLOv2ObjectDetector(trainingData,lgraph,options);

